[package]
name = "cftail"
version = "0.1.0"
authors = ["Simon Walker <swalker@pixsystem.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_cloudformation = "0.45.0"
rusoto_core = "0.45.0"
tokio = { version = "0.2.0", features = ["full"] }
chrono = "0.4.19"
structopt = "0.3.20"
tracing = "0.1.21"
termcolor = "1.1.0"
async-trait = "0.1.41"
