[package]
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
edition = "2018"
name = "cftail"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
chrono = "0.4.19"
rusoto_cloudformation = "0.45.0"
rusoto_core = "0.45.0"
serde = {version = "1.0.117", features = ["derive"]}
serde-xml-rs = "0.4.0"
structopt = "0.3.20"
termcolor = "1.1.0"
tokio = {version = "0.2.0", features = ["full"]}
tracing = "0.1.21"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"

[dev-dependencies]
rusoto_mock = "0.45.0"
