[package]
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
edition = "2018"
name = "cftail"
version = "0.6.2"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
chrono = "0.4.19"
rusoto_cloudformation = { version = "0.47.0", optional = true }
rusoto_core = { version = "0.47.0", optional = true }
serde = {version = "1.0.117", features = ["derive"]}
serde-xml-rs = "0.4.0"
structopt = "0.3.20"
termcolor = "1.1.0"
tokio = {version = "1", features = ["full"]}
tracing = "0.1.21"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
eyre = "0.6.3"
color-eyre = "0.5.7"
thiserror = "1.0.22"
futures = "0.3.15"
term_size = "0.3.2"
notify-rust = "4.5.5"
term-table = "1.3.2"
aws-config = { version = "0.5.2", optional = true }
aws-sdk-cloudformation = { version = "0.5.2", optional = true }
aws-smithy-types = { version = "0.35.2", optional = true }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }

[dev-dependencies]
rusoto_mock = "0.48.0"
env_logger = "*"
log = "*"

[features]
default = ["aws-sdk"]
rusoto = ["rusoto_core", "rusoto_cloudformation"]
aws-sdk = ["aws-config", "aws-sdk-cloudformation", "aws-smithy-types"]

[profile.release]
opt-level = "z"
